# generated by datamodel-codegen:
#   filename:  sim
#   timestamp: 2023-01-12T21:29:46+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class Division(BaseModel):
    id: str
    name: str


class SubLeague(BaseModel):
    divisions: List[Division]
    id: str


class CurrentLeagueData(BaseModel):
    id: str
    name: str
    subLeagues: List[SubLeague]


class SimData(BaseModel):
    banner: str
    currentDay: int
    currentLeagueData: CurrentLeagueData
    currentSeasonId: str
    currentSeasonNumber: int
    isOffseason: bool
    isTournament: bool
    liveGames: bool


class Sim(BaseModel):
    endDayNumber: int
    endTime: str
    phase: str
    simData: SimData
    startDayNumber: int
    startTime: str
