# generated by datamodel-codegen:
#   filename:  https://api2.sibr.dev/mirror/sim
#   timestamp: 2023-01-23T17:10:25+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Division(BaseModel):
    id: str
    name: str


class SubLeague(BaseModel):
    divisions: list[Division]
    id: str


class CurrentLeagueData(BaseModel):
    id: str
    name: str
    sub_leagues: list[SubLeague] = Field(..., alias="subLeagues")


class SimData(BaseModel):
    banner: str
    current_day: int = Field(..., alias="currentDay")
    current_league_data: CurrentLeagueData = Field(..., alias="currentLeagueData")
    current_season_id: str = Field(..., alias="currentSeasonId")
    current_season_number: int = Field(..., alias="currentSeasonNumber")
    is_offseason: bool = Field(..., alias="isOffseason")
    is_tournament: bool = Field(..., alias="isTournament")
    live_games: bool = Field(..., alias="liveGames")


class Sim(BaseModel):
    end_day_number: int = Field(..., alias="endDayNumber")
    end_time: str = Field(..., alias="endTime")
    phase: str
    sim_data: SimData = Field(..., alias="simData")
    start_day_number: int = Field(..., alias="startDayNumber")
    start_time: str = Field(..., alias="startTime")
