# generated by datamodel-codegen:
#   filename:  teams
#   timestamp: 2023-01-12T21:43:23+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class CategoryRating(BaseModel):
    name: str
    stars: float


class Division(BaseModel):
    id: str
    name: str


class Modification(BaseModel):
    backgroundColor: str | None
    color: str | None
    description: str
    icon: str | None
    name: str
    textColor: str | None


class TeamModification(BaseModel):
    modification: Modification
    teamId: str


class PlayerModification(BaseModel):
    modification: Modification
    playerId: str


class RosterSlot(BaseModel):
    active: bool
    location: str
    orderIndex: Optional[int]


class RosterItem(BaseModel):
    id: str
    modifications: List[PlayerModification]
    name: str
    overallRating: float
    rosterSlots: List[RosterSlot]


class Standing(BaseModel):
    losses: int
    seasonId: str
    teamId: str
    wins: int


class Team(BaseModel):
    activeTeam: bool
    attributes: List
    categoryRatings: List[CategoryRating]
    deceased: bool
    division: Division
    emoji: str
    id: str
    locationName: str
    modifications: List[TeamModification]
    name: str
    nickname: str
    primaryColor: str
    roster: List[RosterItem]
    secondaryColor: str
    shorthand: str
    slogan: str
    standings: List[Standing]
